### ISSUE TITLE
App fails to open on Mac

### ISSUE THREAD

**Issue by ghlopez** [lmdu/dockey#1]
Hello, 
I have been following the instructions to install dockey but when I try to open the app it fails to open and I do not getn ya ny sort of messages anywhere. 
I am trying to install in on a MacOS Monterey 12.6 
Any suggestions on what might be going on and how to solve it?
Thanks

**Comment by lmdu** [comment]
I am going to fix these issues. Currently, it only works well on Windows 10, 11 and Ubuntu 20.04. Please wait the version 0.4.0, it's the stable version with robust features.

**Comment by ghlopez** [comment]
Thanks for your prompt reply!

**Comment by rkakamilan** [comment]
I tried to install v0.8.1, v0.8.0, v0.7.0, v0.6.0, v0.5.0, and v0.40, but failed to open the app in any cases with an error "Dockey.app is damaged and can’t be opened. You should move it to the Trash”. 

My PC is MacOS Ventura 13.1, and Apple M1.  Is Dockey compatible with it? Any suggestions on this?

Thanks in advance.

**Comment by lmdu** [comment]
Due to the gatekeeper of MacOS, it will be slightly complicated to install unsigned softwares. You can see our documentation and follow the installation: https://dockey.readthedocs.io/en/latest/installation.html#macos

**Comment by rkakamilan** [comment]
Thanks for your reply. According to your instruction, I disabled the gatekeeper, but I still got the same error. Any other suggestions?

**Comment by lmdu** [comment]
First, make sure `Allow apps downloaded from Anywhere` was checked. And then double click dmg installer, drag Dockey to Application folder. And then run the following command from terminal:
```
sudo xattr -r -d com.apple.quarantine /Applications/Dockey.app
```
If you still have problems, you can show me your screenshot. I did not test on MacOS Ventura, but test on MacOS 11, because my Mac does not support MacOS 12+.

**Comment by rkakamilan** [comment]
Finally made it! Many thanks for the prompt reply and support.

**Comment by sitiazma** [comment]
I am using Mac, how to set the path to Autogrid and Autodock4? The current instruction https://dockey.readthedocs.io/en/latest/docking.html only for Window users.
