### ISSUE TITLE
pose visualization and PLIF analysis

### ISSUE THREAD

**Issue by kathyli2023** [lmdu/dockey#13]
cannot show the docking poses in the PyMOL Sidebar
cannot analyze the interactions

**Comment by lmdu** [comment]
Have you installed openbabel on your machine? If yes, you should uninstall it and restart computer. Otherwise, you can provide the .dock project file for me to test.

**Comment by kathyli2023** [comment]
Please check the attached file. Thanks.



Yan,Li Associate Professor
Department of Medicinal Chemistry, School of Pharmacy
Fudan University 
826 Zhangheng Road,Shanghai 201203
P.R.China 
TEL: 13917945784
-----原始邮件-----
发件人:"Lianming Du" ***@***.***>
发送时间:2023-11-11 11:54:18 (星期六)
收件人: lmdu/dockey ***@***.***>
抄送: "Yan Li" ***@***.***>, Author ***@***.***>
主题: Re: [lmdu/dockey] pose visualization and PLIF analysis (Issue #13)






Have you installed openbabel on your machine? If yes, you should uninstall it and restart computer. Otherwise, you can provide the .dock project file for me to test.

**Comment by lmdu** [comment]
I am sorry, I could not find you attached file. Could you send me the file on github web page. Thanks.

**Comment by kathyli2023** [comment]
Please check the attached file.
[Uploading vs-01.zip…]()

**Comment by lmdu** [comment]
I have clicked the link, but can not download the file. You can send me the file to my email adullb@qq.com.
