### ISSUE TITLE
docking pose not in the defined binding pocket

### ISSUE THREAD

**Issue by kathyli2023** [lmdu/dockey#14]
I defined the binding pocket by drawing custom box, however, the generated docking conformations are not in it.

**Comment by qq764543440** [comment]
我也遇到了同样的问题。对接引擎Autodock4，参数默认。对接结果显示，配体均在设置好的口袋之外。

**Comment by lmdu** [comment]
Ok, I am trying to seek the answer.

**Comment by lmdu** [comment]
我们已经在v0.10.2版本中修复了这个问题，配体可以对接到口袋。

**Comment by kathyli2023** [comment]
已测试，谢谢！


-----原始邮件-----
发件人:"Lianming Du" ***@***.***>
发送时间:2023-11-24 16:40:54 (星期五)
收件人: lmdu/dockey ***@***.***>
抄送: "Yan Li" ***@***.***>, Author ***@***.***>
主题: Re: [lmdu/dockey] docking pose not in the defined binding pocket (Issue #14)






我们已经在v0.10.2版本中修复了这个问题，配体可以对接到口袋。
